### ISSUE TITLE
[701] No 'galaxy_info' found results in meta/requirements.yml file

### ISSUE THREAD

**Issue by toddmichael** [ansible-community/ansible-lint#1096]
### Summary

ansible-lint reporting `[701] No 'galaxy_info' found` in my `meta/requirements.yml`, a file that unlike `meta/main.yml` does not (to my knowledge) support a `galaxy_info` field.

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details

```console (paste below)
$ ansible --version
ansible 2.10.1

$ ansible-lint --version
ansible-lint 4.3.5
```

- ansible installation method: pipenv (pip)
- ansible-lint installation method: pipenv (pip)

##### OS / ENVIRONMENT
MacOS 10.15.7 (Catalina Latest)

##### STEPS TO REPRODUCE

Using this `meta/requirements.yml`
```bash
---

# insert third party deps here. download with:
# ansible-galaxy install -r requirements.yml
# https://docs.ansible.com/ansible/galaxy.html

- name: singleplatform-eng.users
  version: v1.2.6

- name: weareinteractive.sudo
  version: 1.14.1

- name: geerlingguy.fluentd
  version: 1.1.0
```

Note that `meta/main.yml` does include `galaxy_info`, but does not include as dependencies, the roles listed in requirements.yml. This is purposeful because I'm choosing `meta/requirements.yml` instead of `meta/main.yml` because I prefer the workflow and do not want the roles running first, as they do when in `meta/main.yml`.  I'm following the previously linked user-guide on this topic.

To reproduce, I simply run ansible-lint directly or via molecule.

##### Desired Behaviour

I would expect ansible-lint not to flag these as issues... unless I'm completely misunderstanding the finding and misreading the documentation associated with this rule.

##### Actual Behaviour

Below are the ansible-lint results when run on my role.
```bash
$ ansible-lint
[701] No 'galaxy_info' found
meta/requirements.yml:7
{'meta/main.yml': {'name': 'singleplatform-eng.users', 'version': 'v1.2.6', '__line__': 7, '__file__': '/Users/tmichael/orgs/tmb/ansible_roles/base/meta/requirements.yml', 'skipped_rules': []}}

[701] No 'galaxy_info' found
meta/requirements.yml:10
{'meta/main.yml': {'name': 'weareinteractive.sudo', 'version': '1.14.1', '__line__': 10, '__file__': '/Users/tmichael/orgs/tmb/ansible_roles/base/meta/requirements.yml'}}

[701] No 'galaxy_info' found
meta/requirements.yml:13
{'meta/main.yml': {'name': 'geerlingguy.fluentd', 'version': '1.1.0', '__line__': 13, '__file__': '/Users/tmichael/orgs/tmb/ansible_roles/base/meta/requirements.yml'}}
```

**Comment by ssbarnea** [comment]
I am inclined to see this as not a bug, mainly because I am not aware of any Ansible tool documenting presence of reqs files inside meta. Look more like an incorrect layout to me. AFAIK, requirements.yml files are only supported at root level, as in repository root or role root.

I am curious what others think.

**Comment by toddmichael** [comment]
> I am inclined to see this as not a bug, mainly because I am not aware of any Ansible tool documenting presence of reqs files inside meta...

@ssbarnea (et al.), my apologies; it appears I forgot the link to the Galaxy User Guide that documents this new (Ansible 2.10) feature.  Here ya go:

[Galaxy User Guide --> Installing Roles From Galaxy --> Dependencies](https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#dependencies)

> Roles can also be dependent on other roles, and when you install a role that has dependencies, those dependencies will automatically be installed to the roles_path.
>
> There are two ways to define the dependencies of a role:
>  - using meta/requirements.yml
>  - using meta/main.yml
>
> Using meta/requirements.yml (versionadded:: 2.10)
>
> You can create the file meta/requirements.yml and define dependencies in the same format used for requirements.yml described in the Installing multiple roles from a file section.
>
> From there, you can import or include the specified roles in your tasks.

Appreciate the consideration/support.  Love this project!

**Comment by ssbarnea** [comment]
That being introduced in 2.10 explains why I was not aware about it. Please make a PR to address it and I will review it.

For the moment I am unable to fix it myself due to a combination of lack of time and maybe even more important because there is nobody else to review my patch (cannot review mine). That being a reasons why most pending PRs are mine.

**Comment by escalate** [comment]
Hi @ssbarnea ,
I have the same problem with ansible version 2.10.3 and ansible-lint 4.3.7.
The problem is getting bigger because everybody will switch to the new collections syntax.
As an role developers it is necessary to have the requirements.yml file to install necessary collections.
Could you please fix this issue?
I could review your change if you like.
Greetings
Felix

**Comment by ssbarnea** [comment]
@escalate Sad to say but I am overloaded and the only thing I can do is to help reviewing incoming PRs. I wish I would have more time available.

That is a community project and I would be more than happy to welcome new maintainers, even occasional bugfix contributors would be a huge help.
