### ISSUE TITLE
v5.0 has been released but not reflected in CHANGELOG

### ISSUE THREAD

**Issue by sfuerte** [ansible-community/ansible-lint#1338]
The latest entry in `CHANGELOG` is for _4.3.0 - Released 2020-08-17_.

Is it possible to put the full list of changes for 5.0? 

Especially given that there are some breaking changes. 

Thanks a lot in advance!

##### Issue Type

- Bug Report

##### Ansible and Ansible Lint details
```console
ansible --version
ansible 2.10.5
  config file = .../ansible.cfg
  configured module search path = ['/Users/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.7/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.1 (default, Feb  3 2021, 07:38:02) [Clang 12.0.0 (clang-1200.0.32.29)]

ansible-lint --version
ansible-lint 5.0.0
```

**Comment by ssbarnea** [comment]
Apparently you did not read the first sentence from the changelog file at https://github.com/ansible-community/ansible-lint/blob/master/CHANGELOG.rst 

I was considering removing the file as I was aware of risk of confusing people. On the other hand I am aware that the current release notes are incremental, meaning that they report only the changes since the previous release, regardless if it was a pre-release or not. So if you want to know all change made since last 4.x release, you will have to include the in-between release notes.

I will keep this open for a while as I want to gather some feedback from other users before making a decision. Keep in in mind that these release notes are automatically updated based on merged PRs and I do want to keep it this way, as it eases maintenance. The only manual operation that I do sometimes is to remove some totally uninteresting commits that may accidentally be added. Still, as you can see, the notes avery quite detailed.
