### ISSUE TITLE
Recursive symlink created in .cache can prevent pip from installing current repository

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#1566]
Upstream bug https://github.com/pypa/pip/issues/10005 can prevent users of ansible-lint and molecule from installing current repository, as pip would endup with an endless loop trying to copy the code.

We rely on those symlinks in order to avoid copying the source code inside the ansible-environments (where we keep roles and collections used during testing).

As even if pip fixes the bug we will continue to see such problems with users that use older versions of pip, we should consider which workarounds we have. So far I identified:

1. change `.cache` directory default to be `.tox/.cache` as this folder is ignored by pip by default. This is low effort and low risk approach
2. as @tadeboro suggested, start using `~/.cache` for caching. This requires us to use a hash to distinguish between various repositories and also makes me wonder if it may cause other problems when home directory may not be on the same partition as the project_dir, as I am not sure if those symlinks would work. Cleaning up that centralized .cache is another issue that concerns me but we can delay fixing it for a later time (not really being a blocker).

**Comment by alessfg** [comment]
Given the change in the default `.cache` location to `~/.cache`, should the `.cache` location excluded in https://github.com/ansible-community/ansible-lint/pull/1479 also be modified to reflect the new location?

**Comment by ssbarnea** [comment]
There is no need to exclude ~/.cache because is outside current repository anyway, which is almost for sure a subfolder inside user home, or anywhere else, but still never a folder that includes user home directory.

**Comment by alessfg** [comment]
That makes sense -- however, in that case, do you have any suggestions on how to prevent the linter from linting external roles installed by molecule's requirements file ([example here](https://github.com/nginxinc/ansible-role-nginx-app-protect/runs/2732536718?check_suite_focus=true#step:6:19))? (I can open a new issue if you think this might be an actual issue instead of PBKAC.)

**Comment by ssbarnea** [comment]
Just upgrade molecule and the linter to latest versions, remove existing in-repo .cache folder(s) and run again, it should work fine.

**Comment by alessfg** [comment]
So I upgraded both Molecule to `3.3.4` and Ansible lint to `5.0.12`, reran the tests and I'm still seeing the same error, both when executing `ansible-lint` on its own, and when executing `molecule lint`. When executing `ansible-lint` on its own, I can use the `--offline` flag to workaround the issue, but `molecule` installs dependencies before linting as part of its workflow. The issue in the GitHub actions workflow I'm running seems to potentially be due to the [ANSIBLE_ROLES_PATH](https://github.com/nginxinc/ansible-role-nginx-app-protect/runs/2763929578?check_suite_focus=true#step:6:17) used by Ansible lint?
