### ISSUE TITLE
Add support for alternate '.ansible-lint' file locations

### ISSUE THREAD

**Issue by Rickkwa** [ansible-community/ansible-lint#489]
# Issue Type
- Feature request

# Ansible and Ansible Lint details

```
$ ansible --version
ansible 2.4.2.0
  config file = /root/.ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/venvs/lint-4/lib/python2.7/site-packages/ansible
  executable location = /root/venvs/lint-4/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

$ ansible-lint --version
ansible-lint 4.1.0
```

- ansible installation method: OS package (Centos 7)
- ansible-lint installation method: pip

# Desired Behaviour

Support other locations for `.ansible-lint` configuration file other than the current working directory.

For example, similarly to Ansible's `ansible.cfg` [locations](https://docs.ansible.com/ansible/latest/reference_appendices/config.html#the-configuration-file), we can do (in order of priority):
* `-c` (command line flag; currently exists)
* `ANSIBLE_LINT_CONFIG` (environment variable if set)
* `.ansible-lint` (current directory; currently exists)
* `~/.ansible-lint` (in home directory)

I think the environment variable and home directory ones are particularly useful when used in conjunction with Molecule. It let's us define a more "global" default config file instead of going into EVERY SCENARIO to edit `molecule.yml` to point to a common config.

**Comment by tterranigma** [comment]
I would add `XDG_CONFIG_HOME/ansible-lint/config`.

**Comment by zx1986** [comment]
really need this feature too, and I am sourcing for the `.ansible-lint` loading codes.

**Comment by nkakouros** [comment]
@ssbarnea A reason for closing would be appreciated.

**Comment by ssbarnea** [comment]
Sure. Due to lack of time, this feature will likely never be implemented as it too trivial. Use can already specify a custom config file name.

As nobody bothered to make a pull request in almost two years it makes sense to close it, especially as is not a bug. Now features requests and ideas go to discussions, so we can declutter the issue tracker.

It should be noted that closed tickets does not mean I would not review a pull-request for them, it just send the signal that no further action is expected on them. I would personally like to see this implemented as `.config/ansible-lint.yml`, as this would fix two issues at once: declutter the repo root and also assuring we use .yml file extension, as is less problematic with editors.
