### ISSUE TITLE
detect and auto-install requirements.yml before linting

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#930]
In order to avoid errors caused by missing collections the linter should attempt to install `requirements.yml` files when detected.

This would prove especially handy when it called from pre-commit.

One aspect that is not sure is related to the lack of isolation context, as galaxy would install the role to default user location. Is this and acceptable behavior?

**Comment by ssbarnea** [comment]
@dpendolino @webknjaz @awcrosby What do you think? Ok to install them if found? Additional logic should be added to ignore already installed collections as we do not want to fail (or be too slow). IMHO use of `--force` would not be acceptable, due both performance and security.

**Comment by webknjaz** [comment]
I think this defeats the concept of linting:
1) There may be a huge performance penalty
2) It may mutate the environment (which is ultimately bad)
3) It may break assumptions when people upgrade and ansible-lint tries to do something with their env

Besides, the package management aspect should be left to ansible-galaxy CLI

**Comment by ssbarnea** [comment]
We could try to setup our own custom collection path which is isolated from Ansible. This would avoid problem 2. Problem 1 is not a big deal because galaxy will not install a collection if is already installed, but it will likely add ~2s to execution.

Point 3 is bit more complex, if we run in isolation, it will cause some confusions for people that do expect it to reuse current ansible environment.

Whatever we decide to do, it may confuse some users. Still, I hope we do all agree that we need to improve the default experience or we will be flooded with false-bugs about ansible is not able to find my module. Based on current reports I think people assume the presence of requirements.yml file also makes collection installation happen, magically.

Probably it would make sense to open a reddit thread about it, so we would make an informed decision.

**Comment by webknjaz** [comment]
It'd be easier with explicit opt-in via a CLI flag. But w/o it, I'm :-1: on this one.

**Comment by webknjaz** [comment]
Oh, and another thing I wanted to mention is that https://github.com/ansible/ansible-lint/issues/739 needs to be fixed before even attempting this. I don't want to make the security side of it even worse.

**Comment by nwerker** [comment]
We use ansible-lint in linting pipelines and it would drastically increase our linting times if the packages get automatically installed. Maybe there could be an flag on auto-install and it defaults to false?

**Comment by ssbarnea** [comment]
@nwerker Let me put it this way: as of today, you cannot lint without installing all required dependencies and this is not going to change (impossible to validate code without knowning about it, it would kinda similar with a request to make the linter work without having ansible installed). 

How/When/If we decide to install them is subject to the current debate.

Maybe it is not clear but installation would not happen on each run, it would happen only if they are not already installed, as that is what galaxy does.

**Comment by davidmnoriega** [comment]
Setting up a run environment is not the responsibility of a linter

**Comment by MarkusTeufelberger** [comment]
I don't want a linter to run anything that downloads things from the internet. If linting can't happen because some dependencies aren't present, show an error about it and return a non-0 return code. Please do NOT assume that just because a file exists somewhere, you need to start downloading stuff in a linter. This is not the job of ansible-lint, and if people don't understand that, it needs to be fixed in documentation, error messages or procedures, not by trying to be helpful and starting to add in things that are not the job of a linter.

**Comment by ssbarnea** [comment]
This can be implemented as an optional feature, one that is not enabled by default. A very common use case is usage of the linter as a pre-commit hook, which by design isolates the linter instalation from the current evnironment. This also means that even if you have the requirements installed, the linter executed by pre-commit will not have access to them.

I am more than happy to review a PR on this. The optional part should address the concern of those that do not want to have stuff installed by default (even if these may be in isolated environments)
.

**Comment by MarkusTeufelberger** [comment]
This just means that your pre-commit hook needs a `ansible-galaxy install` step in it, if that's a concern, not that `ansible-lint` should be capable of installing dependencies.

**Comment by ssbarnea** [comment]
@MarkusTeufelberger I invite you to dig a little on the architecture of pre-commit tool, http://pre-commit.com as this imposes some design limitations. It is not my tool but it is by far the most popular way to call linters.

**Comment by MarkusTeufelberger** [comment]
Just use a `docker` or `script` hook there instead of a `python` one and you're perfectly able to run ansible-galaxy.

**Comment by MarkusTeufelberger** [comment]
> This can be implemented as an optional feature, one that is not enabled by default.

It wasn't and is now going to mess up my CI system. Great. Not.

**Comment by ssbarnea** [comment]
Lets not mislead users, that change was applies to major 5 version which was not released yet. I doubt it does mess someone's CI system unless is installing the linter from git master branch.

Do you have any idea on how we could improve the implementation? Keep in mind that linting collections is one primary use-case for the linter, it must work without having to add any configuration.

Do you want an offline flag? -- temporary you could use a trick and define `ANSIBLE_COLLECTION_PATH= ANSIBLE_ROLE_PATH=` variables as their presence disables the auto-installation. See https://github.com/ansible-community/ansible-lint/blob/master/src/ansiblelint/_prerun.py#L33

**Comment by MarkusTeufelberger** [comment]
I didn't write "did", I wrote "going to".

I have a `requirements.yml` file in my repository and don't want `ansible-lint` to install anything at all. At most it might(?) try to run `yamllint` on it. About the proposed trick: I invite you to dig a little on the architecture of pre-commit tool, http://pre-commit.com as this imposes some limitations regarding using environment variables to implicitly set something that was conceived as optional and off-by-default. See https://github.com/pre-commit/pre-commit/issues/758

Sorry to be so snarky, but this is _really_ annoying as I'm waiting for a few major versions by now that `ansible-lint` finally becomes stable enough to actually start using and contributing to it without having to worry that it has to be re-done, re-architected or re-written in a few months. Now just to get around adding documentation that `ansible-galaxy install` needs to be called in some cases before `ansible-lint` or switching to `script` in the `.pre-commit-hooks.yaml` file I and every other user of this tool now need to either write angry comments on a closed issue, write my own `pre-commit` hook (again! I already rewrote it several times since the upstream one broke constantly) or get into the code and start fixing this issue myself in my spare time because I won't be able to convince my employer to fix this on the clock. Something I don't look forward to after the bad contributor experience I had last time. :-(

**Comment by ssbarnea** [comment]
Yep, i am quite aware about the architecture limitations of pre-commit and that while is a great tool it also has some notable downsides, including a having a BFDL maintainer, with accent on the "D" part.

In fact one of the reasons for auto installing requirements.yml was to make it easy to use in both pre-commit and tox without having to do preparatory work, hacking ansible variables or preinstalling reqs.

I fully feel your pain regarding tuning `.pre-commit-hooks.yaml` in order to make it run, I had to do these on >30 repos, not a joy.

I will reopen this ticket and assign it 5.0 release in order to not forget to implement an offline option for it. Unless someone has a better idea this is how I plan to implement it:

* Adding `offline: true` to config, defining `OFFLINE=1` or adding `--offline` will disable ansible-galaxy installs and other
any other possible future actions that may require network access to perform the linting.
* Document the feature
* Assure we log as INFO decision to run galaxy-install or to bypass it due to offline mode.

**Comment by MarkusTeufelberger** [comment]
Not sure if I'm 100% happy with the `offline` name, but thanks a lot for implementing this at least in an opt-out manner! :-)
