### ISSUE TITLE
Make unknown file type an implicit error

### ISSUE THREAD

**Issue by ssbarnea** [ansible-community/ansible-lint#986]
##### Summary
Since we introduced file auto-detection logic in the linter we also ignored any file which we were not able to identify as an ansible file, with a message like `Unknown file type: ...`

This caused some serious regressions where we silently failed to raise errors on ansible files that were indeed broken.

##### Details

The heuristic logic for determining if a file should be managed by ansible is almost impossible to perfect, mainly because is solely relies on file and folder names.

Due to this, I propose one major change: making any unrecognized file an error, so user will be forced to update the exclude_path in order to avoid these errors, or fix the internal errors inside the files.

While this error will likely break any usage that relied on auto-detection, it will be very easy to fix and will avoid future confusions.

In order to ease the addition of the skips, the linter will also display a sample file with suggested excludes, making it even easier for the user to do a copy/paste job.

Please use thumb-up thumb-down to vote for or against this proposal, eventually suggest on how we can implement it in a better way.

**Comment by ansiblejunky** [comment]
What is the main detection algorithm used right now and what files are "supported" or detected at the moment? Do we have this documented somewhere?

For Ansible, we have the following breakdown of file types. 

- YAML files, detectable by file extension `yaml` or `yml`
  - Playbooks
  - Role Vars
  - Role Default Vars
  - Role Meta Data
  - Role Tasks
  - Role Handlers
  - Inventory Plugin Config (for dynamic inventory configuration)
- Jinja2 files, detectable by file extension `j2`
  - Jinja2 Templates (used within Role Templates, or anywhere else)
- Python, detectable by file extension `py`
  - Inventory scripts
  - Custom modules (these can be inside `role/library` folder or even in playbook repo `library` or elsewhere)
  - Custom plugins (same as above)
- INI, detectable sometimes by file extension `ini` but often times we would see something like `inventory` without file extension
  - Inventory (static)
  - Inventory script config file (new direction is inventory plugins, but the older inventory script required an INI file to configure the settings)
- Others (not currently supported, JSON, XML, etc)
  - Role Files (can have any time of file contained in the `roles/files` folder)

So for each of those "supported" file types we can detect them initially using file extension and then pass the file and content to the rules runner so that rules can do some additional work on the entire file (such as indentation, etc).  

I would recommend we first determine what we (as Ansible linter) should test for according to best practices. We implemnt those rules within ansible-lint (independent of external tools).  Anything outside of that scope can be tested using an external linter... we can have a config option that allows the developer to enable additional testing with an external linter for specific file types.  

As an example... we can test Python plugin files to check if it complies with ansible plugin writing standards, and then afterwards launch flake8 to do additional checks.

Let me know your thoughts.

**Comment by ssbarnea** [comment]
Closing because it is no longer relevant as we now process any YAML files and we no longer produce errors as described.
